apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build
  namespace: hw-13
spec:
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--dockerfile=/workspace/Dockerfile"
        - "--context=/workspace"
        - "--destination=flask-app:latest"
        - "--no-push"
        volumeMounts:
        - name: build-context
          mountPath: /workspace
      volumes:
      - name: build-context
        configMap:
          name: flask-source
      restartPolicy: Never
  backoffLimit: 3
