[all:children]
web_servers
db_servers

[web_servers]
# web-centos9.elysium-space.com ansible_host=192.168.77.208
web-ubuntu24.elysium-space.com ansible_host=192.168.77.209
# web-debian.elysium-space.com ansible_host=192.168.77.210
# web-fedora.elysium-space.com ansible_host=192.168.77.211

[db_servers]
# db-debian.elysium-space.com ansible_host=192.168.77.212
# db-fedora.elysium-space.com ansible_host=192.168.77.213
db-ubuntu22.elysium-space.com ansible_host=192.168.77.214
# db-centos9.elysium-space.com ansible_host=192.168.77.215

[all:vars]
ansible_user=root
ansible_ssh_pass="1qaz@WSX3edc"  # Only needed for first connection
